import React from "react"

import Patchwork from "../components/patchwork"

const Home = () => (
  <Patchwork>
      <h1>Welcome to your new Gatsby site.</h1>
      <p>Now go build something great.</p>
      <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Fermentum iaculis eu non diam phasellus. Cursus in hac habitasse platea dictumst quisque sagittis purus sit. Justo donec enim diam vulputate ut pharetra sit. Porta lorem mollis aliquam ut porttitor leo a diam. Bibendum at varius vel pharetra vel turpis nunc. Dui nunc mattis enim ut tellus elementum sagittis vitae et. Orci nulla pellentesque dignissim enim sit amet venenatis. Sollicitudin nibh sit amet commodo. Pellentesque elit eget gravida cum. Est ante in nibh mauris. Amet purus gravida quis blandit. Turpis tincidunt id aliquet risus feugiat in ante metus. Semper viverra nam libero justo laoreet. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Mattis pellentesque id nibh tortor.

Ut faucibus pulvinar elementum integer enim. Augue neque gravida in fermentum et sollicitudin. Nec nam aliquam sem et tortor consequat id porta. Euismod nisi porta lorem mollis aliquam ut. Gravida neque convallis a cras. Feugiat pretium nibh ipsum consequat nisl vel pretium. Mi eget mauris pharetra et ultrices neque. Orci sagittis eu volutpat odio facilisis mauris. Etiam dignissim diam quis enim lobortis scelerisque fermentum dui. Sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula. Vel quam elementum pulvinar etiam. Luctus accumsan tortor posuere ac ut consequat. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Viverra adipiscing at in tellus integer feugiat. Justo laoreet sit amet cursus sit amet. Nisl rhoncus mattis rhoncus urna neque viverra.

Pretium aenean pharetra magna ac placerat vestibulum. Mauris ultrices eros in cursus turpis. Id venenatis a condimentum vitae sapien pellentesque. At consectetur lorem donec massa sapien faucibus et. Et odio pellentesque diam volutpat. Habitant morbi tristique senectus et netus et malesuada. Et malesuada fames ac turpis egestas integer eget. Lorem mollis aliquam ut porttitor leo a. Sit amet facilisis magna etiam tempor orci eu. Convallis posuere morbi leo urna molestie at. Semper auctor neque vitae tempus quam pellentesque nec nam aliquam. Diam phasellus vestibulum lorem sed. Non quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Ultricies lacus sed turpis tincidunt id. Ac turpis egestas sed tempus urna. Purus ut faucibus pulvinar elementum integer enim neque volutpat. Congue quisque egestas diam in arcu cursus euismod.

Pharetra vel turpis nunc eget lorem dolor sed. Est sit amet facilisis magna etiam tempor orci eu. Nullam eget felis eget nunc lobortis mattis aliquam faucibus. Est sit amet facilisis magna. Blandit aliquam etiam erat velit scelerisque in dictum non. Nisl rhoncus mattis rhoncus urna neque viverra justo. Arcu cursus euismod quis viverra nibh. Turpis tincidunt id aliquet risus feugiat in ante metus dictum. Feugiat in ante metus dictum at tempor. Id interdum velit laoreet id. Id porta nibh venenatis cras sed felis eget. A condimentum vitae sapien pellentesque. Nulla posuere sollicitudin aliquam ultrices sagittis orci a. Amet massa vitae tortor condimentum. Suspendisse in est ante in nibh mauris cursus mattis. Ipsum consequat nisl vel pretium lectus quam id leo. Arcu dictum varius duis at. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet. Leo vel fringilla est ullamcorper eget nulla facilisi. Aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant.

Id diam vel quam elementum. Netus et malesuada fames ac turpis. Et pharetra pharetra massa massa ultricies. Urna et pharetra pharetra massa massa ultricies. At auctor urna nunc id cursus. Dui nunc mattis enim ut tellus. Tortor at risus viverra adipiscing at in. Risus nec feugiat in fermentum posuere urna nec tincidunt. Vitae purus faucibus ornare suspendisse sed nisi lacus sed. Faucibus in ornare quam viverra. Adipiscing commodo elit at imperdiet dui.

Magna sit amet purus gravida quis blandit turpis cursus. Tincidunt tortor aliquam nulla facilisi cras. Tempor orci eu lobortis elementum nibh tellus. Pretium fusce id velit ut tortor. In est ante in nibh. Mi sit amet mauris commodo quis. Viverra orci sagittis eu volutpat odio facilisis mauris sit amet. Egestas erat imperdiet sed euismod nisi porta lorem. Sociis natoque penatibus et magnis. Scelerisque viverra mauris in aliquam sem fringilla ut. Orci ac auctor augue mauris. Lacus viverra vitae congue eu.

Molestie at elementum eu facilisis sed odio. Purus faucibus ornare suspendisse sed. Nunc faucibus a pellentesque sit. Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra accumsan. Arcu felis bibendum ut tristique. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Et egestas quis ipsum suspendisse ultrices gravida dictum fusce. Vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Egestas fringilla phasellus faucibus scelerisque. Rhoncus mattis rhoncus urna neque viverra justo. In fermentum posuere urna nec tincidunt. Vitae tempus quam pellentesque nec nam aliquam sem et tortor. Lacus luctus accumsan tortor posuere ac ut consequat semper.

Egestas diam in arcu cursus euismod quis viverra nibh cras. Viverra adipiscing at in tellus integer. Posuere ac ut consequat semper viverra nam libero justo. Mattis molestie a iaculis at. Faucibus et molestie ac feugiat sed lectus vestibulum. Quam id leo in vitae turpis massa sed. Semper auctor neque vitae tempus quam. Pharetra pharetra massa massa ultricies mi quis hendrerit dolor. Commodo sed egestas egestas fringilla phasellus faucibus. Luctus accumsan tortor posuere ac ut consequat. Non curabitur gravida arcu ac. Nibh sit amet commodo nulla facilisi nullam vehicula. Malesuada proin libero nunc consequat interdum.

Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Mauris cursus mattis molestie a iaculis at. Senectus et netus et malesuada. Amet nulla facilisi morbi tempus iaculis urna id. Arcu non odio euismod lacinia at quis risus. Sed velit dignissim sodales ut eu sem integer vitae justo. Neque sodales ut etiam sit amet nisl purus in. Dolor sit amet consectetur adipiscing elit pellentesque. Ut diam quam nulla porttitor massa id neque aliquam. Donec enim diam vulputate ut pharetra sit amet. Arcu vitae elementum curabitur vitae. Sit amet dictum sit amet justo donec enim. Leo integer malesuada nunc vel risus commodo viverra maecenas accumsan. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien et.

Viverra vitae congue eu consequat ac. Orci ac auctor augue mauris augue. Duis ultricies lacus sed turpis tincidunt id aliquet risus. Enim blandit volutpat maecenas volutpat blandit aliquam etiam erat. Adipiscing elit ut aliquam purus sit. Ipsum consequat nisl vel pretium lectus quam id leo in. Purus ut faucibus pulvinar elementum integer enim neque. Varius morbi enim nunc faucibus a pellentesque sit. Elementum integer enim neque volutpat ac tincidunt. Diam quis enim lobortis scelerisque fermentum dui faucibus in. A pellentesque sit amet porttitor eget.
      </p>
  </Patchwork>
)

// class Home extends React.Component {

// }

export default Home
